version: '3'
services:
  tracks:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracks
    restart: always
    volumes:
      - ./data/app:/var/www
      - ./data/backups:/backups
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3000:80
